### PR TITLE
Fixing a minor bug where 'width' and 'height' parameters were reversed.

### LINKED ISSUE #497: Saving PNG image bug.
Hi,

When swapping between certain resolutions in map mode through the pause menu, the background screen captured image has what appears to be a stride problem.

Consider the following images

image_one

image_two

Note: This final image is the temporary image from the hard drive.

capture_screen14

I did some limited investigation.  I originally felt that the issue was in the following function

```c++
void ImageMemory::CopyFromImage(BaseTexture *img)
```

However, I am not entirely sure.  The code in this function does appear correct to me.  Maybe I missed something?

### PR DESCRIPTION
**Pull request by authenticate**
Hi,

This is a change to fix #497.

The 'width' and 'height' parameters to the 'Resize' function call were reversed.  This is what caused the image stride issue seen in the screen shots from #497.

Let me know if there are any issues or questions.

Thanks again.

### CODE REVIEW

File: src/engine/video/image_base.cpp [hunk 1]
```diff
@@ -318,9 +320,11 @@ void ImageMemory::RGBAToRGB()
 
 void ImageMemory::CopyFromTexture(TexSheet *texture)
 {
-    Resize(texture->height, texture->width, false);
```
Comment (authenticate) [inline src/engine/video/image_base.cpp]: This is where the parameters were switched.

**Comment by Bertram25** [comment]
Thanks for the fix! I also have to fix travis build now I reactivated it, btw.
