### PR TITLE
Fixed Error 1 error LNK2019 with VisualStudio builds.

### LINKED ISSUE #556: VisualStudio: Error 1 error LNK2019: unresolved external symbol _SDL_main referenced in function _main
Compiling with VisualStudio causes a linking error:

~~~~
Error 1 error LNK2019: unresolved external symbol _SDL_main referenced in function _main
~~~~

This happens because `SDL_main.h` contains the line `#define main SDL_main`

- https://forums.libsdl.org/viewtopic.php?p=6759
- https://stackoverflow.com/questions/6847360/error-lnk2019-unresolved-external-symbol-main-referenced-in-function-tmainc

### PR DESCRIPTION
**Pull request by gunchleoc**
Changed argument signature for main() and ParseProgramOptions() to resolve conflict with SDL_main.h that redefines main.

This fixes #556.

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -1,6 +1,6 @@
 ////////////////////////////////////////////////////////////////////////////////
 //            Copyright (C) 2004-2011 by The Allacrost Project
-//            Copyright (C) 2012-2016 by Bertram (Valyria Tear)
+//            Copyright (C) 2012-2017 by Bertram (Valyria Tear)
```
Comment (akien-mga) [inline src/main.cpp]: Just a side note on good git practices: for future commits it's best to avoid modifying unrelated parts of the file, such as here the copyright header. Those three year bumps are of course not enough as it should be done for every single file in the project, so it's best not to do it at all and have it done for all files at once in their own commit.

No need to change how it is now though, the change doesn't hurt ;)

Comment (gunchleoc) [inline src/main.cpp]: Thanks, I will keep that in mind :)
